"""Async-протоколы репозиториев (docs/03-architecture §domain).

Реализации — :mod:`app.infrastructure.repositories`, принимают
``AsyncSession`` в конструкторе. Носители данных — ORM-модели из
``shared.models``.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from app.domain.entities import Recipient
from shared.models import Delivery, InboundSms, PhoneNumber, Team, TelegramLink, User


class TeamRepository(Protocol):
    async def list_all(self) -> list[Team]: ...
    async def create(self, *, name: str, leader_user_id: int | None = None) -> Team: ...
    async def get(self, team_id: int) -> Team | None: ...
    async def get_by_name(self, name: str) -> Team | None: ...
    async def rename(self, *, team_id: int, name: str) -> None: ...
    async def set_leader(self, *, team_id: int, leader_user_id: int | None) -> None: ...
    async def delete(self, team_id: int) -> None: ...


class PhoneNumberRepository(Protocol):
    async def list_all(self) -> list[PhoneNumber]: ...
    async def list_by_team(self, team_id: int) -> list[PhoneNumber]: ...
    async def list_by_teams(self, team_ids: frozenset[int]) -> list[PhoneNumber]: ...
    async def find_by_phone(self, phone_number: str) -> PhoneNumber | None: ...
    async def get(self, number_id: int) -> PhoneNumber | None: ...
    async def create(
        self,
        *,
        phone_number: str,
        team_id: int,
        added_by_user_id: int | None,
        label: str | None,
    ) -> PhoneNumber: ...
    async def delete(self, number_id: int) -> None: ...


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def list_by_team(self, team_id: int) -> list[User]: ...
    async def recipients_for_team(self, team_id: int) -> list[Recipient]: ...


class UserTeamRepository(Protocol):
    async def add(self, *, user_id: int, team_id: int) -> bool: ...
    async def remove(self, *, user_id: int, team_id: int) -> bool: ...
    async def exists(self, *, user_id: int, team_id: int) -> bool: ...
    async def list_team_ids_for_user(self, user_id: int) -> list[int]: ...
    async def list_team_ids_for_users(
        self, user_ids: list[int]
    ) -> dict[int, list[int]]: ...
    async def list_user_ids_for_team(self, team_id: int) -> list[int]: ...


class TelegramLinkRepository(Protocol):
    async def get_by_telegram_user_id(
        self, telegram_user_id: int
    ) -> TelegramLink | None: ...
    async def get_active_by_telegram_user_id(
        self, telegram_user_id: int
    ) -> TelegramLink | None: ...
    async def upsert(
        self, *, telegram_user_id: int, user_id: int
    ) -> tuple[TelegramLink, bool]: ...
    async def mark_dead(self, telegram_user_id: int) -> None: ...


class SmsRepository(Protocol):
    async def create(
        self,
        *,
        twilio_message_sid: str | None,
        from_number: str,
        to_number: str,
        body: str,
        team_id: int | None,
        raw_payload: dict[str, Any],
    ) -> InboundSms: ...
    async def get(self, sms_id: int) -> InboundSms | None: ...
    async def find_by_sid(self, sid: str) -> InboundSms | None: ...
    async def list_inbound(
        self,
        *,
        to_numbers: list[str] | None,
        to_number: str | None,
        cursor: tuple[datetime, int] | None,
        limit: int,
    ) -> list[InboundSms]: ...


class DeliveryRepository(Protocol):
    async def try_reserve(
        self, *, inbound_sms_id: int, user_id: int, telegram_user_id: int
    ) -> int | None: ...
    async def mark_sent(self, delivery_id: int) -> None: ...
    async def mark_failed(self, delivery_id: int, error_message: str) -> None: ...
    async def mark_dead(self, delivery_id: int, error_message: str) -> None: ...
    async def pending(self, max_attempts: int, limit: int = 100) -> list[Delivery]: ...


class StateRepository(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str) -> None: ...
